### ISSUE TITLE
birdseye allows you to install using a pip that does not match your python

### ISSUE THREAD

**Issue by Almenon** [Almenon/birdseye-vscode#17]
1. Download python 2 and 3
2. Make sure "python" references python 2.
3. Set pip to reference python 3 pip.
4. Launch vscode birdseye - it brings up installation prompt
5. click on install - it installs and says install sucessful
6. Close and reopen birdseye - it brings up same installation prompt.

At step 5 it should warn that the version of python being used does not match the version of pip being used.

I don't see this as a common scenario so this is a low-priority bug.  (Also you can just install manually).  If you run into this please comment below so I can recognize it as higher priority.

**Comment by alexmojaki** [comment]
Instead of the `pip` command, use `python -m pip`.

**Comment by Almenon** [comment]
Good idea! That would solve another problem too in that the user may not
have pip in their path.

On Apr 7, 2018 1:42 AM, "Alex Hall" <notifications@github.com> wrote:

Instead of the pip command, use python -m pip.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Almenon/birdseye-vscode/issues/17#issuecomment-379451317>,
or mute the thread
