### ISSUE TITLE
check for update when user launches birdseye

### ISSUE THREAD

**Issue by Almenon** [Almenon/birdseye-vscode#19]
Birdseye does not provide a \_\_version\_\_ attribute so I would either have to add it in or use pip.

> pip list --outdated

Unfortunately there does not seem to be a pip argument for checking for new updates of only one package. (pip list --oudated lists all of them)

**Comment by alexmojaki** [comment]
`pip show birdseye` gives the version.

**Comment by Almenon** [comment]
@alexmojaki I don't want to just get the version - I want to check if there is a newer version availible.

As a workaround I suppose I could hardcode the latest version into the extension, but then I would have to update that manually each time.  Easier to just parse the output of pip list --outdated

**Comment by Almenon** [comment]
sounds good to me - I'll raise an issue in your repo.

**Comment by alexmojaki** [comment]
As it happens I found another bug and I've already released a version 0.4.1, so you should be able to test this soon. But the version check is cached for a day, so if you've already upgraded to 0.4.0 and run birdseye you won't see it yet.

**Comment by rootsmusic** [comment]
I'm using version 0.0.6 of @Almenon's [extension](https://marketplace.visualstudio.com/items?itemName=almenon.birdseye-vscode), which was updated on 3/7/2021.  There's no message that says "The package birdseye is out of date."  Since the extension is a "wrapper", does that mean its underlying package has been updated to version 0.9.4?

**Comment by alexmojaki** [comment]
When the extension installs birdseye, it should just automatically install the latest version by default.
