### ISSUE TITLE
Doesn't pick up that birdseye is running

### ISSUE THREAD

**Issue by alexmojaki** [Almenon/birdseye-vscode#23]
[The code checks for the string "Running"](https://github.com/Almenon/birdseye-vscode/blob/47b3d6c7c6cc986074f54f4ff8ec5bccea6ca0b1/src/extension.ts#L74) and with the latest version of Flask this doesn't work any more. This is what my server shows:

```
 * Serving Flask app "birdseye" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
WARNING:werkzeug: * Debugger is active!
```

The effect is that the birdseye pane is stuck in "Starting birdseye..."

I think you should rather poll http://localhost:7778/ until you get a response. I can make birdseye explicitly log a message including "Running" but that won't help people who don't upgrade.

**Comment by Almenon** [comment]
You're right, polling would be the best way as it would be immune to future message changes. On the other hand, changing the message I look for is pretty darn easy.  I'll do this if I have time and if not just realease a new version looking for a updated string.

**Comment by Almenon** [comment]
some sample code I'm leaving for myself when I come back to this:

```typescript
const options = {
  host: 'www.google.com',
  port: 80,
  path: '/index.html'
};

http.get(options, function(res) {
  console.log("Got response: " + res.statusCode);

  res.on('error', function(e) {
  console.log("Got error: " + e.message);
});
```
