### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by alexmojaki** [Almenon/birdseye-vscode#24]
I'm now hosting proper documentation. There's a section about this extension here: https://birdseye.readthedocs.io/en/latest/integrations.html#visual-studio-code-extension

Is there anything you'd like me to add there?

I suggest linking to the documentation site rather than the birdseye repo.

**Comment by Almenon** [comment]
Nah that looks good. Thanks!

**Comment by Almenon** [comment]
does the readme look fine? I put in the link to the documentation but I can edit it if you have any changes to suggest.

**Comment by alexmojaki** [comment]
No, someone reading that wouldn't know how to use the extension. They'd decorate their function...and then what? You also need to either point to or copy the VS Code section of the docs.

Also I suggest not giving the instructions about decoration, just point either to the main documentation or the quick start page.

BTW my name is Alex Hall, either write that or alexmojaki.

**Comment by Almenon** [comment]
done.
