### ISSUE TITLE
Interactive elements don't appear in the WebView tab

### ISSUE THREAD

**Issue by hunkyjimpjorps** [Almenon/birdseye-vscode#29]
The extension properly opens a WebView and loads `localhost:7778`, but none of the function call pages have any interactive elements; they just display the timestamp and plain code.  I think this might simply be because the WebView doesn't explicitly allow scripts.

![image](https://user-images.githubusercontent.com/5170341/110219481-7c8c7380-7e8d-11eb-89c7-b318686673b3.png)

**Comment by Almenon** [comment]
resolved w/ https://github.com/Almenon/birdseye-vscode/pull/30
